# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P1jgfOBT--AnofNTU_n7Z01IzPd98FdY
"""

!pip install openai==0.28 -q
import openai
import csv

# Set up OpenAI API key
openai.api_key = 'sk-None-mz9ajHVyDXZYtx4HiHt9T3BlbkFJADmgfooAWgBYqsIe9MBa'

def categorize_services(Description):
    response = openai.Completion.create(
        model="gpt-3.5-turbo",
        prompt=f"Classify the following service description into categories such as bulk email sending, MTA management, email delivery optimization, etc.:\n\n{description}",
        max_tokens=50
    )
    return response.choices[0].text.strip()

# Read the CSV file
input_file = '/content/Task/competitors.csv'
output_file = '/content/Task/filtered_competitors.csv'

try:
    with open(input_file, mode='r', encoding='utf-8') as infile, open(output_file, mode='w', encoding='utf-8', newline='') as outfile:
        reader = csv.DictReader(infile)
        fieldnames = reader.fieldnames + ['Categorized Services']
        writer = csv.DictWriter(outfile, fieldnames=fieldnames)

        writer.writeheader()
        for row in reader:
            description = row['Description']  # Adjust based on actual CSV column name
            categorized_services = categorize_services(description)
            row['Categorized Services'] = categorized_services
            writer.writerow(row)
except FileNotFoundError:
    print(f"Error: The file {input_file} was not found.")
except Exception as e:
    print(f"An error occurred while reading or writing CSV files: {e}")

# Filter the CSV to retain relevant services
try:
    with open(output_file, mode='r', encoding='utf-8') as infile:
        reader = csv.DictReader(infile)
        relevant_companies = [row for row in reader if any(keyword in row['Categorized Services'].lower() for keyword in ['Email','Bulk Email','United States','email sending', 'email delivery'])]

    # Save the filtered results to a new CSV file
    final_output_file = 'relevant_companies.csv'
    with open(final_output_file, mode='w', encoding='utf-8', newline='') as outfile:
        writer = csv.DictWriter(outfile, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(relevant_companies)

    print(f"Filtered relevant companies saved to {final_output_file}")
except FileNotFoundError:
    print(f"Error: The file {output_file} was not found.")
except Exception as e:
    print(f"An error occurred while filtering CSV files: {e}")